on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_release:
        description: "Skip release related steps? (true/false)"
        required: true
        default: "false"

env:
  version: m72-088b74e5

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: ./script/prepare_linux.sh
      - run: python3 script/check_release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
        if: ${{ github.event.inputs.skip_release != 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py --build-type ${{ matrix.build_type }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
      - uses: actions/upload-artifact@v2
        if: ${{ github.event.inputs.skip_release != 'true'}}
        with:
          name: Skia-${{ env.version }}-linux-${{ matrix.build_type }}-x64.zip
          path: "*.zip"
      - run: python3 script/release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
        if: ${{ github.event.inputs.skip_release != 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
